application: pagestickies
version: 1
runtime: python
api_version: 1
default_expiration: "30d 1h"

handlers:

- url: /static
  static_dir: static


- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /services/.*
  script: services/services.py

- url: /p/.*
  script: /p/public.py

- url: /.*
  script: main.py



skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*\.bat)|
 (\..*)|
 )$